import { expect, test } from '@playwright/test'

test('XAMPP: dashboard, implicit Soll, masks and navigation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./')
  await expect(page.getByRole('button', { name: 'Kritisch: 3 Skills anzeigen', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Handlungsbedarf: 7 Skills anzeigen' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Unkritisch: 16 Skills anzeigen' })).toBeVisible()
  await page.getByRole('button', { name: 'Baum', exact: true }).click()
  const root = page.getByRole('button', { name: /Testtaxonomie/ })
  await expect(root).toHaveAttribute('aria-expanded', 'false')
  await expect(root.getByRole('img')).toHaveAttribute('aria-label', 'Kritisch')
  await root.click()
  await expect(page.getByRole('button', { name: /Organisationskompetenzen/ }).getByRole('img')).toHaveAttribute('aria-label', 'Handlungsbedarf')
  await page.getByRole('button', { name: /Datenkompetenzen/ }).click()
  await page.getByRole('button', { name: /Daten verarbeiten und analysieren/ }).click()
  await page.getByRole('button', { name: /Analyse und Daten/ }).click()
  await expect(page.getByRole('heading', { name: 'Analyse und Daten' })).toBeVisible()
  await expect(page.getByText('Migrationsplanung', { exact: true })).toBeVisible()
  await expect(page.getByText('Migrationsplanung', { exact: true }).locator('..').getByRole('img')).toHaveAttribute('aria-label', 'Kritisch')
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption({ label: 'Anna Adler' })
  await expect(page.getByText('Rechengrundlagen', { exact: true }).locator('..').getByRole('img')).toHaveAttribute('aria-label', 'Vorhanden')
  await expect(page.getByRole('button', { name: 'Kritisch: 3 Skills anzeigen', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await page.getByRole('button', { name: /Reset/ }).click()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' })).toHaveValue('1')
  await expect(page.getByRole('button', { name: 'Organisationsmaske', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Handlungsbedarf: 7 Skills anzeigen' }).click()
  await page.getByRole('button', { name: 'Budgetplanung: Details', exact: true }).click()
  await expect(page.getByText('Einziger Wissensträger: Anna Adler')).toBeVisible()
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.getByRole('heading', { name: 'Analyse und Daten' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' })).toHaveValue('1')
  await page.getByRole('button', { name: 'Unkritisch: 16 Skills anzeigen' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(16)
  await page.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(root).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Organisationsmaske', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' }).locator('option:checked')).toHaveText('Keiner')
  await expect(page.getByRole('button', { name: /Zurück/ })).toBeDisabled()
  await page.screenshot({ path: 'test-results/dashboard.png', fullPage: true })
  expect(errors).toEqual([])
})

test('empty Soll, catalog masks, mobile layout and retry', async ({ page, request }) => {
  const response = await request.get('api/analysis')
  const data = await response.json()
  data.skills = []; data.required_skill_ids = []
  data.summary.required_skill_count = 0; data.summary.counts = { red: 0, yellow: 0, green: 0 }
  let failed = true
  await page.route('**/api/analysis', route => route.fulfill({ status: failed ? 503 : 200, json: failed ? { error: {} } : data }))
  await page.goto('./')
  await expect(page.getByRole('alert')).toContainText('nicht erreichbar')
  failed = false
  await page.getByRole('button', { name: 'Erneut versuchen' }).click()
  await expect(page.getByText(/Kein Soll-Bedarf vorhanden/)).toBeVisible()
  await expect(page.locator('.metric-number')).toHaveText(['0', '0', '0'])
  await page.getByRole('button', { name: /Testtaxonomie/ }).click()
  await page.getByRole('button', { name: /Datenkompetenzen/ }).click()
  await page.getByRole('button', { name: /Daten verarbeiten und analysieren/ }).click()
  await page.getByRole('button', { name: /Analyse und Daten/ }).click()
  await expect(page.locator('.skill-list li')).toHaveCount(14)
  await expect(page.locator('.skill-list .neutral')).toHaveCount(14)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Kritisch: 0 Skills anzeigen', exact: true }).click()
  await expect(page.getByText('Leere Liste', { exact: true })).toBeVisible()
})
