import { expect, test } from '@playwright/test'

test('red candidates open personal DAG; full/general/owned and back preserve context', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./')
  await page.getByRole('button', { name: 'Kritisch: 3 Skills anzeigen', exact: true }).click()
  await page.getByRole('button', { name: 'Datenmigration: Details', exact: true }).click()
  const card = page.getByRole('article', { name: 'Datenmigration', exact: true })
  await expect(card.locator('tbody tr')).toHaveCount(3)
  await expect(card.locator('tbody tr').nth(0)).toContainText('Ben Berger')
  await expect(card.locator('tbody tr').nth(0).locator('td').nth(2)).toHaveText('2')
  await card.getByRole('button', { name: 'Pfad für Ben Berger' }).click()
  await expect(page.getByRole('heading', { name: 'Datenmigration', exact: true })).toBeVisible()
  await expect(page.locator('.distance')).toHaveText('Fertigkeitsdistanz: 2')
  await expect(page.getByRole('combobox', { name: 'Pfadumfang' })).toHaveValue('remaining')
  await page.locator('.graph-description summary').click()
  await expect(page.locator('.graph-description li')).toHaveCount(5)
  await expect(page.getByRole('region', { name: /Entwicklungs-DAG/ }).locator('canvas').first()).toBeVisible()
  await page.getByRole('combobox', { name: 'Pfadumfang' }).selectOption('full')
  await expect(page.locator('.distance')).toHaveText('Fertigkeitsdistanz: 2')
  await page.getByRole('combobox', { name: 'Person im Entwicklungspfad' }).selectOption('')
  await expect(page.locator('.distance')).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Pfadumfang' })).toHaveCount(0)
  await page.getByRole('button', { name: 'DAG vergrößern' }).click()
  await page.getByRole('button', { name: /Reset/ }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/development-general.png', fullPage: true })
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.getByRole('heading', { name: 'Kritisch', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Datenmigration: Details', exact: true })).toHaveAttribute('aria-expanded', 'true')
  expect(errors).toEqual([])
})

test('green table is skill-first and opens general path despite selected person', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption({ label: 'Anna Adler' })
  await page.getByRole('button', { name: 'Unkritisch: 16 Skills anzeigen' }).click()
  await expect(page.locator('thead th').first()).toHaveText('Skill-Bezeichnung')
  await expect(page.locator('tbody tr')).toHaveCount(16)
  await page.getByRole('button', { name: 'Datenanalyse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('')
  await page.getByRole('combobox', { name: 'Person im Entwicklungspfad' }).selectOption('1')
  await expect(page.locator('.distance')).toHaveText('Fertigkeitsdistanz: 0')
  await page.locator('.graph-description summary').click()
  await expect(page.locator('.graph-description li')).toHaveCount(1)
  await expect(page.locator('.graph-description li')).toContainText('vorhanden')
  await page.getByRole('combobox', { name: 'Pfadumfang' }).selectOption('full')
  await expect(page.locator('.graph-description li')).toHaveCount(4)
  await expect(page.locator('.distance')).toHaveText('Fertigkeitsdistanz: 0')
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' })).toHaveValue('1')
})

test('four-level taxonomy hides free catalog skills until unmasked and warns without opening DAG', async ({ page }) => {
  await page.goto('./')
  for (const name of ['Testtaxonomie', 'Datenkompetenzen', 'Daten verarbeiten und analysieren', 'Analyse und Daten']) {
    await page.getByRole('button', { name: new RegExp(name) }).click()
  }
  await expect(page.getByRole('button', { name: 'Geodatenkartierung', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Geodatenkartierung', exact: true }).locator('..').getByRole('img')).toHaveAttribute('aria-label', 'Ohne Soll-Bewertung')
  await page.getByRole('button', { name: 'Geodatenkartierung', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toContainText('kein geschätzter Entwicklungspfad')
  await expect(page.locator('.view-heading h2')).toHaveText('Analyse und Daten')
  await page.getByRole('button', { name: 'OK', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Datenverständnis', exact: true }).click()
  await page.locator('.graph-description summary').click()
  await expect(page.locator('.graph-description li')).toHaveCount(1)
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.getByRole('heading', { name: /Analyse und Daten/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Organisationsmaske', exact: true })).toHaveAttribute('aria-pressed', 'false')
})

test('yellow excludes carrier, shows recommendations and three explicit slots', async ({ page, request }) => {
  const response = await request.get('api/analysis')
  const data = await response.json()
  // UI-only edge case: two available suggestions. No database mutation.
  const entry = data.development.candidates.find((item: { skill_id: number }) => item.skill_id === 14)
  entry.slots[2] = null; entry.recommendations.unfilled_slots = true
  await page.route('**/api/analysis', route => route.fulfill({ json: data }))
  await page.goto('./')
  await page.getByRole('button', { name: 'Handlungsbedarf: 7 Skills anzeigen' }).click()
  await page.getByRole('button', { name: 'Budgetplanung: Details', exact: true }).click()
  const card = page.getByRole('article', { name: 'Budgetplanung', exact: true })
  await expect(card).toContainText('Einziger Wissensträger: Anna Adler')
  await expect(card.locator('tbody')).not.toContainText('Anna Adler')
  await expect(card.locator('tbody tr')).toHaveCount(3)
  await expect(card.locator('tbody tr').last().locator('td').nth(2)).toBeEmpty()
  await expect(card).not.toContainText('Zusätzlichen Personaleinsatz')
  await expect(card).toContainText('Nicht alle Kandidatenplätze sind besetzt')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/candidates.png', fullPage: true })
})
