import { expect, test, type Page } from '@playwright/test'

async function matrix(page: Page) { await page.getByRole('button', { name: 'Matrix', exact: true }).click() }
async function changeOrganisation(page: Page, id: string) {
  const response = page.waitForResponse(r => r.url().includes('/api/analysis') && r.url().includes(`organisation=${id}`))
  await page.getByRole('combobox', { name: 'Organisationseinheit' }).selectOption(id)
  expect((await response).ok()).toBe(true)
  await expect(page.locator('.taxonomy-node')).toHaveCount(1)
}
test('organisation selection isolates data, resets all context and scenario selection only changes tasks', async ({ page, request }) => {
  await page.goto('./')
  await expect(page.getByRole('combobox', { name: 'Organisationseinheit' }).locator('option:not([value="add"])')).toHaveCount(3)
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Anna Adler' }).uncheck()
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await page.getByRole('button', { name: 'Szenario Kernaufgaben aktivieren' }).click()
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await expect(page.getByRole('checkbox', { name: 'Beschaffung vorbereiten' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Sicherheitsvorfall bearbeiten' })).toBeChecked()
  await expect(page.getByRole('dialog').locator('.simulation-fields > div').nth(1).locator('input:checked')).toHaveCount(2)
  await expect(page.getByRole('checkbox', { name: 'Anna Adler' })).not.toBeChecked()
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  await matrix(page)
  await changeOrganisation(page, '2')
  await expect(page.getByRole('button', { name: 'Graph', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /Zurück/ })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await matrix(page)
  await expect(page.locator('.map-person')).toHaveText(['Tina Test','Tom Test','Tessa Test'])
  await changeOrganisation(page, '3')
  await matrix(page)
  await expect(page.locator('.map-person')).toHaveText(['Vera Versuch','Viktor Versuch','Viola Versuch'])
  await changeOrganisation(page, '1')
  await expect(page.locator('.metric-number')).toHaveText(['3','7','16'])
  expect((await request.get('api/analysis?organisation=2&excluded_employees=1')).status()).toBe(400)
  expect((await request.get('api/analysis?organisation=999')).status()).toBe(400)
  for (const id of [1,2,3]) {
    const data = await (await request.get(`api/analysis?organisation=${id}`)).json()
    for (const scenario of data.simulation.scenarios) expect(scenario.task_ids.every((task: number) => data.simulation.tasks.some((t: {id: number}) => t.id === task))).toBe(true)
  }
})

test('matrix paths, tooltips and multi-person filtering leave organisational numbers unchanged', async ({ page }) => {
  await page.goto('./'); await matrix(page)
  const row = page.locator('[data-map-skill="1"]')
  await expect(row.locator('.map-path')).toHaveText('4')
  await expect(page.getByRole('columnheader', { name: 'Pfad', exact: true })).toHaveAttribute('title', 'Gesamtlänge des allgemeinen Entwicklungspfad')
  await expect(page.locator('[data-map-skill="14"] .map-status')).toHaveAttribute('title', 'Handlungsbedarf • Entwicklungskandidaten anzeigen')
  await page.locator('.matrix-filter summary').click()
  await page.getByRole('checkbox', { name: 'Anna Adler' }).check()
  await page.getByRole('checkbox', { name: 'Ben Berger' }).check()
  await page.locator('.matrix-filter summary').click()
  await expect(page.locator('.map-person')).toHaveCount(2)
  await expect(row.locator('.map-available')).toHaveText('3')
  await page.getByRole('button', { name: 'Graph', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' }).locator('option:checked')).toHaveText('Keiner')
  await matrix(page)
  await expect(page.locator('.map-person')).toHaveCount(5)
  await page.locator('.matrix-filter summary').click()
  await page.getByRole('checkbox', { name: 'Anna Adler' }).check()
  await page.getByRole('checkbox', { name: 'Ben Berger' }).check()
  await page.locator('.matrix-filter summary').click()
  await row.getByRole('button', { name: 'Datenanalyse: Unkritisch öffnen' }).click()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' }).locator('option:checked')).toHaveText('Keiner')
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.locator('.map-person')).toHaveCount(5)
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await expect(page.locator('[data-map-skill="27"] .map-path')).toHaveText('–')
  const free = page.getByRole('button', { name: 'Geodatenkartierung', exact: true })
  await free.scrollIntoViewIfNeeded()
  const scroll = await page.locator('.skill-map-scroll').evaluate(el => el.scrollTop)
  await free.click()
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.locator('#path-warning-description').click()
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.mouse.click(10, 10)
  await expect(page.getByRole('alertdialog')).toHaveCount(0)
  await expect.poll(() => page.locator('.skill-map-scroll').evaluate(el => el.scrollTop)).toBe(scroll)
  await expect(free).toBeFocused()
  await free.click()
  await page.getByRole('button', { name: 'OK', exact: true }).click()
  await expect.poll(() => page.locator('.skill-map-scroll').evaluate(el => el.scrollTop)).toBe(scroll)
  await expect(free).toBeFocused()
  await page.getByRole('button', { name: /Reset/ }).click()
  await page.screenshot({ path: 'test-results/extensions-matrix.png', fullPage: true })
})

test('failed organisation change preserves current data and retry commits the new organisation', async ({ page }) => {
  await page.goto('./'); await matrix(page)
  let fail = true
  await page.route('**/api/analysis?organisation=2', route => fail ? route.fulfill({ status: 503, json: { error: {} } }) : route.continue())
  await page.getByRole('combobox', { name: 'Organisationseinheit' }).selectOption('2')
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.locator('.metric-number')).toHaveText(['3','7','16'])
  await expect(page.getByRole('combobox', { name: 'Organisationseinheit' })).toHaveValue('1')
  await expect(page.locator('.map-person')).toHaveCount(5)
  fail = false
  await page.getByRole('button', { name: 'Erneut versuchen' }).click()
  await expect(page.getByRole('combobox', { name: 'Organisationseinheit' })).toHaveValue('2')
  await expect(page.locator('.metric-number')).toHaveText(['1','3','4'])
  await expect(page.getByRole('button', { name: 'Graph', exact: true })).toHaveAttribute('aria-pressed','true')
})

test('distance boundary, shared dropdown, status-list navigation and personal non-clickable circles', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Handlungsbedarf: 7 Skills anzeigen' }).click()
  await page.getByRole('button', { name: 'Budgetplanung: Details', exact: true }).click()
  const card = page.getByRole('article', { name: 'Budgetplanung', exact: true })
  await expect(card).not.toContainText('Zusätzlichen Personaleinsatz')
  await page.getByRole('combobox', { name: 'Maximale Distanz' }).selectOption('2')
  await expect(card).toContainText('mehr als 2')
  await expect(card.getByText('Unbesetzt – keine weitere interne Person')).toHaveCount(3)
  await page.getByRole('button', { name: 'Kritisch: 3 Skills anzeigen' }).click()
  await expect(page.getByRole('combobox', { name: 'Maximale Distanz' })).toHaveValue('2')
  await page.getByRole('button', { name: 'Datenmigration: Details', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Datenmigration', exact: true }).getByText('Unbesetzt – keine weitere interne Person')).toHaveCount(1)
  await page.getByRole('button', { name: 'Start', exact: true }).click()
  for (const name of ['Testtaxonomie','Datenkompetenzen','Daten verarbeiten und analysieren','Analyse und Daten']) await page.getByRole('button', { name: new RegExp(name) }).click()
  await page.getByRole('button', { name: 'Datenmigration: Kritisch öffnen' }).click()
  await expect(page.getByRole('button', { name: 'Datenmigration: Details', exact: true })).toHaveAttribute('aria-expanded','true')
  await expect(page.getByRole('combobox', { name: 'Maximale Distanz' })).toHaveValue('3')
  await page.getByRole('button', { name: /Zurück/ }).click()
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption('1')
  await expect(page.locator('.skill-list .status-link')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Datenmigration', exact: true }).locator('..').getByRole('img')).toHaveAttribute('title','Nicht vorhanden')
})
