import { expect, test } from '@playwright/test'

test('organisation dummy stays last, preserves simulation and view, and leaves real switching functional', async ({ page }) => {
  const analysisRequests: string[] = []
  page.on('request', request => { if (request.url().includes('/api/analysis')) analysisRequests.push(request.url()) })
  await page.goto('./')
  const select = page.getByRole('combobox', { name: 'Organisationseinheit' })
  await expect(select).toBeEnabled()
  await expect(select.locator('option').last()).toHaveText('Hinzufügen...')
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Anna Adler' }).uncheck()
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  await page.getByRole('button', { name: 'Matrix', exact: true }).click()
  await expect(page.locator('.metric-number')).toHaveText(['6', '4', '16'])
  const before = analysisRequests.length
  const popup = page.getByRole('alertdialog', { name: 'Organisationseinheit hinzufügen' })
  for (const close of ['button', 'outside', 'escape']) {
    await select.focus()
    await select.selectOption('add')
    await expect(popup).toBeVisible()
    await expect(popup).toContainText('Dummy')
    await expect(popup).toContainText('zukünftige Erweiterbarkeit')
    await expect(select).toHaveValue('1')
    await popup.locator('p').click()
    await expect(popup).toBeVisible()
    if (close === 'button') {
      await page.setViewportSize({ width: 390, height: 844 })
      expect(await popup.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
      await popup.screenshot({ path: 'test-results/organisation-dummy-mobile.png' })
      await popup.getByRole('button', { name: 'Verstanden' }).click()
    } else if (close === 'outside') await page.mouse.click(5, 5)
    else await page.keyboard.press('Escape')
    await expect(popup).toHaveCount(0)
    await expect(select).toBeFocused()
    await expect(select).toHaveValue('1')
    await expect(page.getByRole('button', { name: 'Matrix', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('.metric-number')).toHaveText(['6', '4', '16'])
    expect(analysisRequests.length).toBe(before)
  }
  await select.selectOption('2')
  await expect(page.locator('.metric-number')).toHaveText(['1', '3', '4'])
  await expect(select).toHaveValue('2')
  await expect(page.getByRole('button', { name: 'Graph', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(select.locator('option').last()).toHaveText('Hinzufügen...')
  await select.selectOption('add')
  await popup.getByRole('button', { name: 'Verstanden' }).click()
  await expect(select).toHaveValue('2')
})
