import { expect, test, type Page } from '@playwright/test'

const menu = (page: Page) => page.getByRole('dialog', { name: 'Ausfall simulieren' })
async function change(page: Page, action: () => Promise<unknown>) {
  const response = page.waitForResponse(response => response.url().includes('/api/analysis'))
  await action()
  expect((await response).ok()).toBe(true)
  await expect(menu(page).locator('fieldset')).toBeEnabled()
}
async function openMenu(page: Page) { await page.getByRole('button', { name: 'Simulation', exact: true }).click() }
async function closeMenu(page: Page) { await menu(page).getByRole('button', { name: 'Schließen', exact: true }).click() }

test('employee exclusion updates dashboard, carriers and candidates; current filters survive Back and Reset', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption('1')
  await page.getByRole('button', { name: 'Handlungsbedarf: 7 Skills anzeigen' }).click()
  await page.getByRole('button', { name: 'Budgetplanung: Details', exact: true }).click()
  await page.getByRole('button', { name: 'Budgetplanung', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('1')
  await page.getByRole('combobox', { name: 'Person im Entwicklungspfad' }).selectOption('1')
  await openMenu(page)
  await change(page, () => menu(page).getByRole('checkbox', { name: 'Anna Adler' }).uncheck())
  await closeMenu(page)
  await expect(page.locator('.metric-number')).toHaveText(['6', '4', '16'])
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('')
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' }).locator('option')).not.toContainText(['Anna Adler'])
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.getByRole('heading', { name: 'Handlungsbedarf', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Budgetplanung: Details', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: /Reset/ }).click()
  await expect(page.locator('.metric-number')).toHaveText(['6', '4', '16'])
  await page.getByRole('button', { name: 'Kritisch: 6 Skills anzeigen', exact: true }).click()
  await page.getByRole('button', { name: 'Budgetplanung: Details', exact: true }).click()
  const card = page.getByRole('article', { name: 'Budgetplanung', exact: true })
  await expect(card.locator('tbody')).not.toContainText('Anna Adler')
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await openMenu(page)
  await expect(menu(page).getByRole('checkbox', { name: 'Anna Adler' })).not.toBeChecked()
  await change(page, () => menu(page).getByRole('checkbox', { name: 'Anna Adler' }).check())
  await closeMenu(page)
  await expect(page.locator('.metric-number')).toHaveText(['3', '7', '16'])
})

test('all employees excluded: red demand, no candidates; both excluded: zero and full catalog', async ({ page }) => {
  await page.goto('./')
  await openMenu(page)
  await change(page, () => menu(page).getByRole('button', { name: 'Alle Mitarbeitenden ausschließen' }).click())
  await closeMenu(page)
  await expect(page.locator('.metric-number')).toHaveText(['26', '0', '0'])
  await page.getByRole('button', { name: 'Kritisch: 26 Skills anzeigen', exact: true }).click()
  await page.getByRole('button', { name: 'Datenmigration: Details', exact: true }).click()
  const card = page.getByRole('article', { name: 'Datenmigration', exact: true })
  await expect(card.getByText('Unbesetzt – keine weitere interne Person')).toHaveCount(3)
  for (const row of await card.locator('tbody tr').all()) await expect(row.locator('td').nth(2)).toBeEmpty()
  await expect(card).toContainText('Nicht alle Kandidatenplätze')
  await openMenu(page)
  await change(page, () => menu(page).getByRole('button', { name: 'Alle Aufgaben ausschließen' }).click())
  await closeMenu(page)
  await expect(page.locator('.metric-number')).toHaveText(['0', '0', '0'])
  await page.getByRole('button', { name: /Zurück/ }).click()
  for (const name of ['Testtaxonomie', 'Datenkompetenzen', 'Daten verarbeiten und analysieren', 'Analyse und Daten']) await page.getByRole('button', { name: new RegExp(name) }).click()
  await expect(page.locator('.skill-list li')).toHaveCount(14)
  await page.getByRole('button', { name: 'Datenverständnis', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('')
  await page.locator('.graph-description summary').click()
  await expect(page.locator('.graph-description li')).toHaveCount(1)
  await page.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.locator('.metric-number')).toHaveText(['3', '7', '16'])
  await expect(page.getByRole('button', { name: /Testtaxonomie/ })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: /Zurück/ })).toBeDisabled()
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
})

test('task exclusion changes only demand; closing/reopening preserves filters; reload clears them', async ({ page }) => {
  await page.goto('./')
  await openMenu(page)
  await change(page, () => menu(page).getByRole('checkbox', { name: 'Beschaffung vorbereiten' }).uncheck())
  await page.keyboard.press('Escape')
  await expect(page.locator('.metric-number')).toHaveText(['3', '3', '16'])
  await openMenu(page)
  await expect(menu(page).getByRole('checkbox', { name: 'Beschaffung vorbereiten' })).not.toBeChecked()
  await expect(menu(page).getByRole('checkbox', { name: 'Anna Adler' })).toBeChecked()
  await change(page, () => menu(page).getByRole('button', { name: 'Alle Aufgaben ausschließen' }).click())
  await closeMenu(page)
  await expect(page.locator('.metric-number')).toHaveText(['0', '0', '0'])
  await page.reload()
  await expect(page.locator('.metric-number')).toHaveText(['3', '7', '16'])
  await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'false')
})

test('failed recalculation retains a consistent snapshot; retry applies the filter', async ({ page }) => {
  await page.goto('./')
  let failed = true
  await page.route('**/api/analysis?*', async route => {
    if (failed) await route.fulfill({ status: 503, json: { error: {} } })
    else await route.continue()
  })
  await openMenu(page)
  await menu(page).getByRole('checkbox', { name: 'Anna Adler' }).uncheck()
  await expect(menu(page).getByRole('alert')).toContainText('letzte erfolgreich berechnete Stand')
  await expect(menu(page).getByRole('checkbox', { name: 'Anna Adler' })).toBeChecked()
  failed = false
  await change(page, () => menu(page).getByRole('button', { name: 'Erneut versuchen' }).click())
  await closeMenu(page)
  await expect(page.locator('.metric-number')).toHaveText(['6', '4', '16'])
})

test('Reset retains personal full DAG and exclusions; Back keeps exclusions introduced on the DAG', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Kritisch: 3 Skills anzeigen', exact: true }).click()
  await page.getByRole('button', { name: 'Datenmigration: Details', exact: true }).click()
  await page.getByRole('button', { name: 'Pfad für Ben Berger' }).click()
  await page.getByRole('combobox', { name: 'Pfadumfang' }).selectOption('full')
  await openMenu(page)
  await change(page, () => menu(page).getByRole('checkbox', { name: 'Anna Adler' }).uncheck())
  await closeMenu(page)
  await page.getByRole('button', { name: 'DAG vergrößern' }).click()
  await page.getByRole('button', { name: /Reset/ }).click()
  await expect(page.getByRole('combobox', { name: 'Pfadumfang' })).toHaveValue('full')
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('2')
  await expect(page.locator('.distance')).toHaveText('Fertigkeitsdistanz: 2')
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(page.getByRole('button', { name: 'Datenmigration: Details', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.metric-number')).toHaveText(['6', '4', '16'])
  await openMenu(page)
  await page.screenshot({ path: 'test-results/simulation.png', fullPage: true })
})
