import { expect, test, type Page } from '@playwright/test'

const row = (page: Page, id: number) => page.locator(`[data-map-skill="${id}"]`)
async function map(page: Page) { await page.getByRole('button', { name: 'Karte', exact: true }).click() }
async function back(page: Page) { await page.getByRole('button', { name: /Zurück/ }).click() }
async function simulate(page: Page, label: string) {
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  const response = page.waitForResponse(r => r.url().includes('/api/analysis'))
  await page.getByRole('button', { name: label, exact: true }).click()
  expect((await response).ok()).toBe(true)
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
}

test('map matches API ownership including implicit skills; mask and personal context survive all view switches', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  const data = await (await request.get('api/analysis')).json()
  await page.goto('./')
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption('1')
  await page.getByRole('button', { name: /^Testtaxonomie:/ }).click()
  await map(page)
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' })).toHaveCount(0)
  await expect(page.locator('[data-map-skill]')).toHaveCount(26)
  for (const skill of data.skills) {
    const current = row(page, skill.id)
    await expect(current.locator('.map-available')).toHaveText(String(skill.carrier_count))
    await expect(current.locator('.map-needed')).toHaveText('2')
    await expect(current.locator('.map-gap')).toHaveText(String(Math.max(0, 2 - skill.carrier_count)))
    await expect(current.locator('.possession')).toHaveText(data.employees.map((employee: { available_skill_ids: number[] }) => employee.available_skill_ids.includes(skill.id) ? '✓' : '×'))
  }
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await expect(page.locator('[data-map-skill]')).toHaveCount(29)
  await expect(row(page, 27).locator('.map-needed')).toHaveText('0')
  await expect(row(page, 27).locator('.map-gap')).toHaveText('0')
  await expect(row(page, 27).locator('.map-status')).toHaveCount(0)
  await page.getByRole('button', { name: 'Baum', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' })).toHaveValue('1')
  await expect(page.getByRole('button', { name: /Testtaxonomie/ })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: 'Graph', exact: true }).click()
  await expect(page.locator('.taxonomy-node')).toHaveCount(4)
  await map(page)
  await expect(page.locator('[data-map-skill]')).toHaveCount(29)
  await expect(page.locator('.metric-number')).toHaveText(['3', '7', '16'])
  await page.locator('.skill-map-scroll').screenshot({ path: 'test-results/skill-map-desktop.png' })
  expect(errors).toEqual([])
})

test('map links open general/personal paths, warnings and focused red/yellow/green categories; Back restores scroll', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption('1')
  await map(page)
  await row(page, 1).getByRole('button', { name: 'Datenanalyse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('')
  await back(page)
  await page.getByRole('button', { name: 'Graph', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Mitarbeitermaske' })).toHaveValue('1')
  await map(page)
  await row(page, 1).getByRole('button', { name: /Anna Adler: vorhanden/ }).click()
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('1')
  await expect(page.locator('.distance')).toContainText('0')
  await back(page)
  await row(page, 20).getByRole('button', { name: /Ben Berger: fehlt/ }).click()
  await expect(page.getByRole('combobox', { name: 'Person im Entwicklungspfad' })).toHaveValue('2')
  await expect(page.locator('.distance')).toContainText('2')
  await back(page)
  for (const [id, name, status] of [[20, 'Datenmigration', 'Kritisch'], [14, 'Budgetplanung', 'Handlungsbedarf'], [1, 'Datenanalyse', 'Unkritisch']] as const) {
    const button = row(page, id).getByRole('button', { name: `${name}: ${status} öffnen`, exact: true })
    await button.scrollIntoViewIfNeeded()
    const scroll = await page.locator('.skill-map-scroll').evaluate(el => el.scrollTop)
    await button.click()
    await expect(page.locator(`[data-category-skill="${id}"]`)).toBeFocused()
    if (id !== 1) await expect(page.getByRole('button', { name: `${name}: Details`, exact: true })).toHaveAttribute('aria-expanded', 'true')
    await back(page)
    await expect.poll(() => page.locator('.skill-map-scroll').evaluate(el => el.scrollTop)).toBe(scroll)
  }
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await row(page, 27).getByRole('button', { name: 'Geodatenkartierung', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('kein geschätzter Entwicklungspfad')
  await page.getByRole('button', { name: 'Warnung schließen' }).click()
  await row(page, 27).getByRole('button', { name: /Anna Adler: fehlt/ }).click()
  await expect(page.getByRole('alert')).toContainText('kein geschätzter Entwicklungspfad')
  await page.getByRole('button', { name: 'Warnung schließen' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.skill-map-scroll').evaluate(el => { el.scrollLeft = 300; el.scrollTop = 180 })
  await page.waitForTimeout(100)
  const saved = await page.locator('.skill-map-scroll').evaluate(el => ({ x: el.scrollLeft, y: el.scrollTop }))
  await page.getByRole('button', { name: 'Graph', exact: true }).click(); await map(page)
  await expect.poll(() => page.locator('.skill-map-scroll').evaluate(el => ({ x: el.scrollLeft, y: el.scrollTop }))).toEqual(saved)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.skill-map-scroll').screenshot({ path: 'test-results/skill-map-mobile.png' })
  await page.getByRole('button', { name: /Reset/ }).click()
  await expect.poll(() => page.locator('.skill-map-scroll').evaluate(el => el.scrollLeft + el.scrollTop)).toBe(0)
})

test('map simulation removes columns, recomputes gaps, retains current filters through navigation and handles empty demand', async ({ page }) => {
  await page.goto('./'); await map(page)
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  const response = page.waitForResponse(r => r.url().includes('/api/analysis'))
  await page.getByRole('checkbox', { name: 'Anna Adler' }).uncheck(); await response
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  await expect(page.locator('.map-person')).toHaveCount(4)
  await expect(page.locator('.map-person')).not.toContainText(['Anna Adler'])
  await expect(row(page, 14).locator('.map-available')).toHaveText('0')
  await expect(row(page, 14).locator('.map-gap')).toHaveText('2')
  await row(page, 14).getByRole('button', { name: 'Budgetplanung: Kritisch öffnen' }).click()
  await back(page)
  await expect(page.locator('.map-person')).toHaveCount(4)
  await page.getByRole('button', { name: 'Baum', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Simulation', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await map(page)
  await simulate(page, 'Alle Mitarbeitenden ausschließen')
  await expect(page.locator('.map-person')).toHaveCount(0)
  await expect(row(page, 1).locator('.map-gap')).toHaveText('2')
  await simulate(page, 'Alle Aufgaben ausschließen')
  await expect(page.locator('[data-map-skill]')).toHaveCount(29)
  await expect(page.locator('.map-status')).toHaveCount(0)
  await expect(page.locator('.map-gap')).toHaveText(Array(29).fill('0'))
  await simulate(page, 'Alle Mitarbeitenden einschließen')
  await expect(page.locator('.map-person')).toHaveCount(5)
  await expect(row(page, 1).locator('.map-available')).toHaveText('3')
  await expect(row(page, 1).locator('.map-needed')).toHaveText('0')
  await page.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.locator('.taxonomy-node')).toHaveCount(1)
  await map(page)
  await expect(page.locator('[data-map-skill]')).toHaveCount(26)
  await expect(page.locator('.map-person')).toHaveCount(5)
})
