import { expect, test } from '@playwright/test'

test('multiple roots, empty groups and skills assigned directly to an inner group remain accessible', async ({ page, request }) => {
  const data = await (await request.get('api/analysis')).json()
  const root = data.taxonomy.groups.find((group: { parent_skill_group_id: number | null }) => group.parent_skill_group_id === null)
  data.taxonomy.groups.push({ id: 9999, name: 'Leere Testgruppe', parent_skill_group_id: null })
  const skill = data.taxonomy.skills.find((item: { id: number }) => data.required_skill_ids.includes(item.id))
  skill.skill_group_id = root.id
  await page.route('**/api/analysis', route => route.fulfill({ json: data }))
  await page.goto('./')
  await expect(page.locator('.taxonomy-node')).toHaveCount(1)
  await expect(page.getByRole('button', { name: /^Leere Testgruppe:/ })).toHaveCount(0)
  await page.getByRole('button', { name: /^Testtaxonomie:/ }).click()
  await page.getByRole('button', { name: /Direkt zugeordnete Skills \(1\)/ }).click()
  await expect(page.locator('.skill-list li')).toHaveCount(1)
  await expect(page.locator('.skill-list')).toContainText(skill.name)
})

test('graph: counts, expansion, tree switch, leaf list, Back, zoom and Reset', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./')
  const nodes = page.locator('.taxonomy-node')
  const root = page.getByRole('button', { name: /^Testtaxonomie:/ })
  await expect(nodes).toHaveCount(1)
  await expect(root.locator('.node-count')).toHaveText('26')
  await expect(root).toHaveClass(/red/)
  await root.click()
  await expect(nodes).toHaveCount(4)
  await page.getByRole('button', { name: /^Datenkompetenzen:/ }).click()
  await page.getByRole('button', { name: /^Daten verarbeiten und analysieren:/ }).click()
  await expect(nodes).toHaveCount(6)
  await page.locator('.taxonomy-graph-frame').screenshot({ path: 'test-results/taxonomy-graph-expanded.png' })
  await root.click()
  await expect(nodes).toHaveCount(1)
  await root.click()
  await expect(nodes).toHaveCount(6)
  await page.getByRole('button', { name: 'Baum', exact: true }).click()
  await expect(page.getByRole('button', { name: /Analyse und Daten/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Testtaxonomie/ })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: 'Graph', exact: true }).click()
  await page.getByRole('button', { name: /^Analyse und Daten:/ }).click()
  await expect(page.locator('.skill-list li')).toHaveCount(13)
  await page.getByRole('button', { name: /Zurück/ }).click()
  await expect(nodes).toHaveCount(6)
  const transform = await page.locator('.taxonomy-canvas > g').getAttribute('transform')
  await page.getByRole('button', { name: 'Taxonomie vergrößern', exact: true }).click()
  await expect(page.locator('.taxonomy-canvas > g')).not.toHaveAttribute('transform', transform!)
  const canvas = page.locator('.taxonomy-canvas')
  const bounds = (await canvas.boundingBox())!
  const zoomed = await page.locator('.taxonomy-canvas > g').getAttribute('transform')
  await page.mouse.move(bounds.x + 20, bounds.y + 20)
  await page.mouse.down(); await page.mouse.move(bounds.x + 80, bounds.y + 40); await page.mouse.up()
  await expect(page.locator('.taxonomy-canvas > g')).not.toHaveAttribute('transform', zoomed!)
  await page.getByRole('button', { name: /Reset/ }).click()
  await expect(nodes).toHaveCount(1)
  await root.focus(); await page.keyboard.press('Enter')
  await expect(nodes).toHaveCount(4)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(root).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.taxonomy-graph-frame').screenshot({ path: 'test-results/taxonomy-graph-mobile.png' })
  expect(errors).toEqual([])
})

test('graph reuses mask, possession and simulation ratings, including empty demand', async ({ page }) => {
  await page.goto('./')
  const root = page.getByRole('button', { name: /^Testtaxonomie:/ })
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await expect(root.locator('.node-count')).toHaveText('29')
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption('1')
  await expect(root).toHaveClass(/red/)
  await root.click()
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await expect(page.getByRole('button', { name: /^Organisationskompetenzen:/ })).toHaveClass(/red/)
  await page.getByRole('combobox', { name: 'Mitarbeitermaske' }).selectOption({ label: 'Keiner' })
  await expect(page.getByRole('button', { name: /^Organisationskompetenzen:/ })).toHaveClass(/yellow/)
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await page.getByRole('button', { name: 'Alle Aufgaben ausschließen', exact: true }).click()
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  await expect(root.locator('.node-count')).toHaveText('29')
  await expect(root).toHaveClass(/neutral/)
  await expect(page.locator('.metric-number')).toHaveText(['0', '0', '0'])
})
