import { expect, test } from '@playwright/test'

test('outside clicks dismiss employee dropdown and simulation while retaining selection and filters', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Matrix', exact: true }).click()
  const filter = page.locator('.matrix-filter')
  await filter.locator('summary').click()
  await page.getByRole('checkbox', { name: 'Anna Adler' }).check()
  await expect(filter).toHaveAttribute('open', '')
  await page.getByRole('heading', { name: 'Skill-Taxonomie', exact: true }).click()
  await expect(filter).not.toHaveAttribute('open')
  await expect(page.locator('.map-person')).toHaveText(['Anna Adler'])
  await filter.locator('summary').click()
  await expect(page.getByRole('checkbox', { name: 'Anna Adler' })).toBeChecked()
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Ausfall simulieren' })
  await expect(filter).not.toHaveAttribute('open')
  await dialog.getByRole('heading', { name: 'Ausfall simulieren', exact: true }).click()
  await expect(dialog).toBeVisible()
  await page.getByRole('checkbox', { name: 'Anna Adler' }).uncheck()
  await expect(dialog.locator('fieldset')).toBeEnabled()
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.metric-number')).toHaveText(['6','4','16'])
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Anna Adler' })).not.toBeChecked()
  const bounds = (await dialog.boundingBox())!
  await page.mouse.move(bounds.x + 30, bounds.y + 30)
  await page.mouse.down(); await page.mouse.move(5,5); await page.mouse.up()
  await expect(dialog).toBeVisible()
  await page.mouse.click(5,5)
  await expect(dialog).toHaveCount(0)
})

test('tooltips match the click action, path label is underlined and warning fits on desktop', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Matrix', exact: true }).click()
  for (const [id, text] of [[20,'Kritisch • Entwicklungskandidaten anzeigen'],[14,'Handlungsbedarf • Entwicklungskandidaten anzeigen'],[1,'Unkritisch • Wissensträger anzeigen']] as const) {
    const circle = page.locator(`[data-map-skill="${id}"] .map-status`)
    await expect(circle).toHaveAttribute('title',text)
    await expect(circle.locator('.status-dot')).toHaveAttribute('title',text)
  }
  await expect(page.locator('.tooltip-label')).toHaveCSS('text-decoration-line','underline')
  await page.getByRole('button', { name: 'Handlungsbedarf: 7 Skills anzeigen' }).click()
  await expect(page.locator('.distance-limit')).toHaveAttribute('title','Maximale Distanz zu Zielskills für Entwicklungskandidaten')
  await page.getByRole('button', { name: /Zurück/ }).click()
  await page.getByRole('button', { name: 'Organisationsmaske', exact: true }).click()
  await page.getByRole('button', { name: 'Geodatenkartierung', exact: true }).click()
  const dialog = page.getByRole('alertdialog')
  await expect(dialog).toBeVisible()
  expect(await page.locator('#path-warning-description').evaluate(element => {
    const range = document.createRange(); range.selectNodeContents(element)
    return range.getClientRects().length
  })).toBe(1)
  await dialog.screenshot({ path: 'test-results/warning-width.png' })
  await page.mouse.click(5,5)
  await expect(dialog).toHaveCount(0)
})

test('scenario buttons are local and numbered by position, with up to nine configured entries', async ({ page, request }) => {
  const units = await Promise.all([1,2,3].map(async id => (await request.get(`api/analysis?organisation=${id}`)).json()))
  const ids = units.map(unit => unit.simulation.scenarios.map((s: {id:number}) => s.id))
  expect(new Set(ids.flat()).size).toBe(9)
  await page.goto('./')
  await page.getByRole('combobox', { name: 'Organisationseinheit' }).selectOption('2')
  await expect(page.locator('.metric-number')).toHaveText(['1','3','4'])
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await expect(page.locator('.scenario-buttons button')).toHaveText(['1','2','3'])
  await expect(page.locator('.scenario-buttons button').first()).toHaveAttribute('title','Szenario Kernaufgaben aktivieren')
  await page.getByRole('button', { name: 'Szenario Kernaufgaben aktivieren' }).click()
  await expect(page.getByRole('dialog').locator('fieldset')).toBeEnabled()
  await expect(page.getByRole('checkbox', { name: 'Test: Daten analysieren' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Test: Migration begleiten' })).not.toBeChecked()

  // Synthetic API fixture tests >3, cap at 9, and IDs unrelated to visible labels.
  const data = units[0]
  data.simulation.scenarios = Array.from({length:10}, (_, index) => ({id:15 + index * 7, name:`Testfall ${index + 1}`, task_ids:[9]}))
  await page.route('**/api/analysis', route => route.fulfill({json:data}))
  await page.goto('./')
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await expect(page.locator('.scenario-buttons button')).toHaveText(['1','2','3','4','5','6','7','8','9'])
  await expect(page.locator('.scenario-buttons button').last()).toHaveAttribute('title','Szenario Testfall 9 aktivieren')
  await page.setViewportSize({width:390,height:844})
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByRole('dialog').screenshot({path:'test-results/scenarios-mobile.png'})
  data.simulation.scenarios = []
  await page.goto('./')
  await page.getByRole('button', { name: 'Simulation', exact: true }).click()
  await expect(page.locator('.scenario-buttons button')).toHaveCount(0)
})
